//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEASModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.MemberInfo = new HashSet<MemberInfo>();
        }
    
        public int id { get; set; }
        public int startYear { get; set; }
        public int endYear { get; set; }
        public int semester { get; set; }
        public string courseName { get; set; }
        public string courseTime { get; set; }
        public string classroom { get; set; }
        public string teacher { get; set; }
        public int dayOfWeek { get; set; }
        public int startSection { get; set; }
        public int endSection { get; set; }
        public int startWeek { get; set; }
        public int endWeek { get; set; }
        public int everyWeek { get; set; }
    
        public virtual ICollection<MemberInfo> MemberInfo { get; set; }
    }
}
