//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEASModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupInfo
    {
        public GroupInfo()
        {
            this.MessageInfo = new HashSet<MessageInfo>();
        }
    
        public int Id { get; set; }
        public string GroupTitle { get; set; }
        public Nullable<int> GroupCount { get; set; }
        public string Remark { get; set; }
    
        public virtual ICollection<MessageInfo> MessageInfo { get; set; }
    }
}
