//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEASModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberInfo
    {
        public MemberInfo()
        {
            this.Course = new HashSet<Course>();
            this.GroupInfo = new HashSet<GroupInfo>();
        }
    
        public int Id { get; set; }
        public string MemberId { get; set; }
        public string SName { get; set; }
        public string MemberPwd { get; set; }
        public string ImageUrl { get; set; }
        public string MemberMark { get; set; }
        public Nullable<int> GroupId { get; set; }
    
        public virtual ICollection<Course> Course { get; set; }
        public virtual ICollection<GroupInfo> GroupInfo { get; set; }
    }
}
