//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEASModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageInfo
    {
        public int Id { get; set; }
        public string MessageTitle { get; set; }
        public string MessageContent { get; set; }
        public string PushTime { get; set; }
    }
}
