//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEASModel.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsInfo
    {
        public int Id { get; set; }
        public string author { get; set; }
        public int newType { get; set; }
        public string publishTime { get; set; }
        public string source { get; set; }
        public string newBodyHtml { get; set; }
        public string title { get; set; }
        public string imageUrl { get; set; }
    }
}
