//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MEASWeb.pushService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fc.qust.com/", ConfigurationName="pushService.MyPushServiceDelegate")]
    public interface MyPushServiceDelegate {
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MEASWeb.pushService.PushMessageResponse PushMessage(MEASWeb.pushService.PushMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MEASWeb.pushService.PushMessageResponse> PushMessageAsync(MEASWeb.pushService.PushMessageRequest request);
        
        // CODEGEN: 命名空间  的元素名称 arg0 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        MEASWeb.pushService.PushMessageByTopicResponse PushMessageByTopic(MEASWeb.pushService.PushMessageByTopicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<MEASWeb.pushService.PushMessageByTopicResponse> PushMessageByTopicAsync(MEASWeb.pushService.PushMessageByTopicRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushMessage", Namespace="http://fc.qust.com/", Order=0)]
        public MEASWeb.pushService.PushMessageRequestBody Body;
        
        public PushMessageRequest() {
        }
        
        public PushMessageRequest(MEASWeb.pushService.PushMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class PushMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public PushMessageRequestBody() {
        }
        
        public PushMessageRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushMessageResponse", Namespace="http://fc.qust.com/", Order=0)]
        public MEASWeb.pushService.PushMessageResponseBody Body;
        
        public PushMessageResponse() {
        }
        
        public PushMessageResponse(MEASWeb.pushService.PushMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class PushMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public PushMessageResponseBody() {
        }
        
        public PushMessageResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushMessageByTopicRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushMessageByTopic", Namespace="http://fc.qust.com/", Order=0)]
        public MEASWeb.pushService.PushMessageByTopicRequestBody Body;
        
        public PushMessageByTopicRequest() {
        }
        
        public PushMessageByTopicRequest(MEASWeb.pushService.PushMessageByTopicRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class PushMessageByTopicRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        public PushMessageByTopicRequestBody() {
        }
        
        public PushMessageByTopicRequestBody(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PushMessageByTopicResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PushMessageByTopicResponse", Namespace="http://fc.qust.com/", Order=0)]
        public MEASWeb.pushService.PushMessageByTopicResponseBody Body;
        
        public PushMessageByTopicResponse() {
        }
        
        public PushMessageByTopicResponse(MEASWeb.pushService.PushMessageByTopicResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class PushMessageByTopicResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public PushMessageByTopicResponseBody() {
        }
        
        public PushMessageByTopicResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyPushServiceDelegateChannel : MEASWeb.pushService.MyPushServiceDelegate, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyPushServiceDelegateClient : System.ServiceModel.ClientBase<MEASWeb.pushService.MyPushServiceDelegate>, MEASWeb.pushService.MyPushServiceDelegate {
        
        public MyPushServiceDelegateClient() {
        }
        
        public MyPushServiceDelegateClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyPushServiceDelegateClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPushServiceDelegateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyPushServiceDelegateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MEASWeb.pushService.PushMessageResponse MEASWeb.pushService.MyPushServiceDelegate.PushMessage(MEASWeb.pushService.PushMessageRequest request) {
            return base.Channel.PushMessage(request);
        }
        
        public int PushMessage(string arg0) {
            MEASWeb.pushService.PushMessageRequest inValue = new MEASWeb.pushService.PushMessageRequest();
            inValue.Body = new MEASWeb.pushService.PushMessageRequestBody();
            inValue.Body.arg0 = arg0;
            MEASWeb.pushService.PushMessageResponse retVal = ((MEASWeb.pushService.MyPushServiceDelegate)(this)).PushMessage(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MEASWeb.pushService.PushMessageResponse> MEASWeb.pushService.MyPushServiceDelegate.PushMessageAsync(MEASWeb.pushService.PushMessageRequest request) {
            return base.Channel.PushMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<MEASWeb.pushService.PushMessageResponse> PushMessageAsync(string arg0) {
            MEASWeb.pushService.PushMessageRequest inValue = new MEASWeb.pushService.PushMessageRequest();
            inValue.Body = new MEASWeb.pushService.PushMessageRequestBody();
            inValue.Body.arg0 = arg0;
            return ((MEASWeb.pushService.MyPushServiceDelegate)(this)).PushMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MEASWeb.pushService.PushMessageByTopicResponse MEASWeb.pushService.MyPushServiceDelegate.PushMessageByTopic(MEASWeb.pushService.PushMessageByTopicRequest request) {
            return base.Channel.PushMessageByTopic(request);
        }
        
        public int PushMessageByTopic(string arg0, string arg1) {
            MEASWeb.pushService.PushMessageByTopicRequest inValue = new MEASWeb.pushService.PushMessageByTopicRequest();
            inValue.Body = new MEASWeb.pushService.PushMessageByTopicRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            MEASWeb.pushService.PushMessageByTopicResponse retVal = ((MEASWeb.pushService.MyPushServiceDelegate)(this)).PushMessageByTopic(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MEASWeb.pushService.PushMessageByTopicResponse> MEASWeb.pushService.MyPushServiceDelegate.PushMessageByTopicAsync(MEASWeb.pushService.PushMessageByTopicRequest request) {
            return base.Channel.PushMessageByTopicAsync(request);
        }
        
        public System.Threading.Tasks.Task<MEASWeb.pushService.PushMessageByTopicResponse> PushMessageByTopicAsync(string arg0, string arg1) {
            MEASWeb.pushService.PushMessageByTopicRequest inValue = new MEASWeb.pushService.PushMessageByTopicRequest();
            inValue.Body = new MEASWeb.pushService.PushMessageByTopicRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            return ((MEASWeb.pushService.MyPushServiceDelegate)(this)).PushMessageByTopicAsync(inValue);
        }
    }
}
